require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'UdacityFlashcards' do
  use_unimodules!(exclude: [
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
    'unimodules-face-detector-interface',
    'unimodules-sensors-interface',
  ])
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'UdacityFlashcardsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.75.0' }) # https://stackoverflow.com/a/66071245/4034572
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'UdacityFlashcards-tvOS' do
  # Pods for UdacityFlashcards-tvOS

  target 'UdacityFlashcards-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
